name: base
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - nodejs
  - yarn
  - configurable-http-proxy
  - hatchling
  - jupyterhub
  - jupyterlab
  - dockerspawner
  - jupyterhub-idle-culler

 